const questions = [
  {
    qNo: 1,
    summary: "भारत का सबसे बड़ा राज्य कौनसा है?",
    options: [
      { oNo: 1, text: "उत्तर प्रदेश", isCorrect: true },
      { oNo: 2, text: "महाराष्ट्र", isCorrect: false },
      { oNo: 3, text: "राजस्थान", isCorrect: false },
      { oNo: 4, text: "मध्य प्रदेश", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 2,
    summary: "भारत की सबसे ऊँची चोटी कौनसी है?",
    options: [
      { oNo: 1, text: "माउंट एवरेस्ट", isCorrect: true },
      { oNo: 2, text: "कांगचेंजुँगा", isCorrect: false },
      { oNo: 3, text: "नंदा देवी", isCorrect: false },
      { oNo: 4, text: "मकालु", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 3,
    summary: "भारत का राष्ट्रीय फूल क्या है?",
    options: [
      { oNo: 1, text: "कमल", isCorrect: true },
      { oNo: 2, text: "गुलाब", isCorrect: false },
      { oNo: 3, text: "सनफ्लावर", isCorrect: false },
      { oNo: 4, text: "गेंदा", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 4,
    summary: "भारतीय संविधान कब लागू हुआ था?",
    options: [
      { oNo: 1, text: "1947", isCorrect: false },
      { oNo: 2, text: "1950", isCorrect: true },
      { oNo: 3, text: "1942", isCorrect: false },
      { oNo: 4, text: "1945", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 5,
    summary: "भारत का सबसे लंबा नदी कौन सी है?",
    options: [
      { oNo: 1, text: "यमुना", isCorrect: false },
      { oNo: 2, text: "गंगा", isCorrect: false },
      { oNo: 3, text: "गोदावरी", isCorrect: true },
      { oNo: 4, text: "कृष्णा", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 6,
    summary: "भारत का सबसे बड़ा शहर कौनसा है?",
    options: [
      { oNo: 1, text: "मुंबई", isCorrect: false },
      { oNo: 2, text: "कोलकाता", isCorrect: false },
      { oNo: 3, text: "दिल्ली", isCorrect: true },
      { oNo: 4, text: "बैंगलोर", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 7,
    summary: "ताजमहल कहाँ स्थित है?",
    options: [
      { oNo: 1, text: "दिल्ली", isCorrect: false },
      { oNo: 2, text: "आगरा", isCorrect: true },
      { oNo: 3, text: "जयपुर", isCorrect: false },
      { oNo: 4, text: "लखनऊ", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 8,
    summary: "भारत की सबसे बड़ी झील कौनसी है?",
    options: [
      { oNo: 1, text: "दाल झील", isCorrect: false },
      { oNo: 2, text: "वुलर झील", isCorrect: false },
      { oNo: 3, text: "चिल्का झील", isCorrect: true },
      { oNo: 4, text: "पुलिकट झील", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 9,
    summary: "भारतीय संगीत के प्रमुख राग कौन-कौन से हैं?",
    options: [
      { oNo: 1, text: "यमन", isCorrect: false },
      { oNo: 2, text: "भैरव", isCorrect: true },
      { oNo: 3, text: "हिन्दोल", isCorrect: false },
      { oNo: 4, text: "भैरों", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 10,
    summary: "भारत की सबसे पुरानी राजमहल कहाँ स्थित है?",
    options: [
      { oNo: 1, text: "दिल्ली", isCorrect: false },
      { oNo: 2, text: "आगरा", isCorrect: false },
      { oNo: 3, text: "वाराणसी", isCorrect: false },
      { oNo: 4, text: "पटलिपुत्र", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 11,
    summary: "भारतीय सम्राट अशोक की राजधानी कौन-कौन सी थी?",
    options: [
      { oNo: 1, text: "पाटलिपुत्र", isCorrect: false },
      { oNo: 2, text: "अयोध्या", isCorrect: false },
      { oNo: 3, text: "मथुरा", isCorrect: false },
      { oNo: 4, text: "पटना", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 12,
    summary: "भारतीय स्वतंत्रता सेनानी भगत सिंह का जन्म स्थान क्या है?",
    options: [
      { oNo: 1, text: "आगरा", isCorrect: false },
      { oNo: 2, text: "फरीदकोट", isCorrect: true },
      { oNo: 3, text: "जालंधर", isCorrect: false },
      { oNo: 4, text: "लाहौर", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 13,
    summary: "भारतीय साहित्य के महाकवि तुलसीदास की कौन-सी रचना है?",
    options: [
      { oNo: 1, text: "रामचरितमानस", isCorrect: true },
      { oNo: 2, text: "शकुंतला", isCorrect: false },
      { oNo: 3, text: "कुमारसम्भव", isCorrect: false },
      { oNo: 4, text: "मेघदूत", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 14,
    summary: "भारतीय नृत्य शैली 'कथक' किस राज्य से सम्बंधित है?",
    options: [
      { oNo: 1, text: "राजस्थान", isCorrect: true },
      { oNo: 2, text: "महाराष्ट्र", isCorrect: false },
      { oNo: 3, text: "उत्तर प्रदेश", isCorrect: false },
      { oNo: 4, text: "केरल", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 15,
    summary: "भारत की संविधान सभा का सभापति कौन थे?",
    options: [
      { oNo: 1, text: "राजेन्द्र प्रसाद", isCorrect: true },
      { oNo: 2, text: "भीमराव अंबेडकर", isCorrect: false },
      { oNo: 3, text: "जवाहरलाल नेहरू", isCorrect: false },
      { oNo: 4, text: "सरदार पटेल", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 16,
    summary: "भारतीय संविधान में कितने अनुच्छेद हैं?",
    options: [
      { oNo: 1, text: "395", isCorrect: false },
      { oNo: 2, text: "396", isCorrect: false },
      { oNo: 3, text: "397", isCorrect: true },
      { oNo: 4, text: "398", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 17,
    summary: "भारत की सबसे ऊँची मूर्ति कौन सी है?",
    options: [
      { oNo: 1, text: "बुद्ध पद्मिनी", isCorrect: false },
      { oNo: 2, text: "वीर शिवाजी", isCorrect: false },
      { oNo: 3, text: "स्टैच्यू ऑफ यूनिटी", isCorrect: true },
      { oNo: 4, text: "महात्मा गांधी", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 18,
    summary: "भारतीय राष्ट्रीय ध्वज का रंग क्या है?",
    options: [
      { oNo: 1, text: "सफेद", isCorrect: false },
      { oNo: 2, text: "हरा", isCorrect: false },
      { oNo: 3, text: "भूरा", isCorrect: true },
      { oNo: 4, text: "नीला", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 19,
    summary: "भारतीय राष्ट्रगान के लेखक कौन हैं?",
    options: [
      { oNo: 1, text: "रवीन्द्रनाथ टैगोर", isCorrect: false },
      { oNo: 2, text: "सरोजिनी नायडू", isCorrect: false },
      { oNo: 3, text: "बंकिम चंद्र चट्टोपाध्याय", isCorrect: false },
      { oNo: 4, text: "रविन्द्र नाथ ठाकुर", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 20,
    summary: "भारतीय वायुसेना का स्थापना दिवस कब मनाया जाता है?",
    options: [
      { oNo: 1, text: "8 अक्टूबर", isCorrect: false },
      { oNo: 2, text: "14 अप्रैल", isCorrect: true },
      { oNo: 3, text: "15 अगस्त", isCorrect: false },
      { oNo: 4, text: "5 दिसम्बर", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 21,
    summary: "भारत का सबसे पुराना नगर क्या है?",
    options: [
      { oNo: 1, text: "बनारस", isCorrect: false },
      { oNo: 2, text: "हरिद्वार", isCorrect: false },
      { oNo: 3, text: "अयोध्या", isCorrect: false },
      { oNo: 4, text: "उज्जैन", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 22,
    summary: "भारतीय राष्ट्रीय ध्वज में कितने तिरंगे होते हैं?",
    options: [
      { oNo: 1, text: "2", isCorrect: false },
      { oNo: 2, text: "3", isCorrect: false },
      { oNo: 3, text: "4", isCorrect: false },
      { oNo: 4, text: "5", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 23,
    summary: "भारतीय राष्ट्रगान का नाम क्या है?",
    options: [
      { oNo: 1, text: "जन गण मन", isCorrect: true },
      { oNo: 2, text: "सारे जहाँ से अच्छा", isCorrect: false },
      { oNo: 3, text: "वन्दे मातरम", isCorrect: false },
      { oNo: 4, text: "आओ बच्चों तुम्हें दिखाएं", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 24,
    summary: "कौन सा खेल भारत में नाचने की कला है?",
    options: [
      { oNo: 1, text: "भारतनाट्यम", isCorrect: false },
      { oNo: 2, text: "कथक", isCorrect: false },
      { oNo: 3, text: "ओड़िसी", isCorrect: false },
      { oNo: 4, text: "कुछिपुड़िया", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 25,
    summary: "भारत का सबसे बड़ा वन्यजन्तु अभ्यारण्य कहाँ स्थित है?",
    options: [
      { oNo: 1, text: "जिम्बाब्वे", isCorrect: false },
      { oNo: 2, text: "काजीरंगा", isCorrect: true },
      { oNo: 3, text: "नामधारा", isCorrect: false },
      { oNo: 4, text: "सुल्तानपुर", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 26,
    summary: "बिहार का सबसे बड़ा नगर कौन सा है?",
    options: [
      { oNo: 1, text: "पटना", isCorrect: false },
      { oNo: 2, text: "गया", isCorrect: false },
      { oNo: 3, text: "भागलपुर", isCorrect: false },
      { oNo: 4, text: "मुजफ्फरपुर", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 27,
    summary: "बिहार की सरकारी राजभाषा क्या है?",
    options: [
      { oNo: 1, text: "हिंदी", isCorrect: false },
      { oNo: 2, text: "उर्दू", isCorrect: false },
      { oNo: 3, text: "मैथिली", isCorrect: false },
      { oNo: 4, text: "बोजपुरी", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 28,
    summary: "बिहार के किस नदी पर 'गांधी सेतु' स्थित है?",
    options: [
      { oNo: 1, text: "सोन", isCorrect: false },
      { oNo: 2, text: "गंगा", isCorrect: true },
      { oNo: 3, text: "कोसी", isCorrect: false },
      { oNo: 4, text: "गंडक", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 29,
    summary: "बिहार की सबसे पुरानी नगरी कौन सी है?",
    options: [
      { oNo: 1, text: "नालंदा", isCorrect: true },
      { oNo: 2, text: "मधुबनी", isCorrect: false },
      { oNo: 3, text: "मुजफ्फरपुर", isCorrect: false },
      { oNo: 4, text: "वैशाली", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 30,
    summary: "बिहार का सबसे ऊँचा पर्वत शिखर कौन सा है?",
    options: [
      { oNo: 1, text: "विनायक", isCorrect: false },
      { oNo: 2, text: "नंदा देवी", isCorrect: false },
      { oNo: 3, text: "मौंट अबू", isCorrect: false },
      { oNo: 4, text: "कुँज", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 31,
    summary: "भारतीय सम्राट अशोक का वार्षिक सम्मेलन कहाँ हुआ था?",
    options: [
      { oNo: 1, text: "सारनाथ", isCorrect: false },
      { oNo: 2, text: "पाटलिपुत्र", isCorrect: false },
      { oNo: 3, text: "बोधगया", isCorrect: false },
      { oNo: 4, text: "सैयदपुर", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 32,
    summary: "भारतीय इतिहास में 'मौर्य साम्राज्य' किस युग में था?",
    options: [
      { oNo: 1, text: "वेदिक", isCorrect: false },
      { oNo: 2, text: "महाजनपद", isCorrect: false },
      { oNo: 3, text: "मौर्य", isCorrect: true },
      { oNo: 4, text: "गुप्त", isCorrect: false },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 33,
    summary: "भारतीय नाट्यशास्त्र के अनुसार, रास",
    options: [
      { oNo: 1, text: "बरतने", isCorrect: false },
      { oNo: 2, text: "नृत्य", isCorrect: false },
      { oNo: 3, text: "नृत", isCorrect: false },
      { oNo: 4, text: "रास", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 34,
    summary: "भारत का सबसे लंबा समुद्रतट कौन सा है?",
    options: [
      { oNo: 1, text: "आंध्र", isCorrect: false },
      { oNo: 2, text: "केरल", isCorrect: false },
      { oNo: 3, text: "तमिलनाडु", isCorrect: false },
      { oNo: 4, text: "गुजरात", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
  {
    qNo: 35,
    summary: "भारतीय राष्ट्रीय पक्षी क्या है?",
    options: [
      { oNo: 1, text: "मैना", isCorrect: false },
      { oNo: 2, text: "हंस", isCorrect: false },
      { oNo: 3, text: "मोर", isCorrect: false },
      { oNo: 4, text: "पीपल", isCorrect: true },
    ],
    marks: { positive: 2, negative: 0.5 },
  },
];

export default questions;
